language: python

python:
  - "3.5"
  - "3.4"
  - "2.7"

env:
  - DJANGO="django<=1.8.999"
  - DJANGO="django<=1.11.999"
  - DJANGO="django<=2.0.999"
  - DJANGO="django<=2.1.999"

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO="django<=2.0.999"
    - python: "2.7"
      env: DJANGO="django<=2.1.999"

install:
  - pip install $DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - python setup.py -q install

script:
  - py.test -v --pep8

notifications:
  email:
    recipients:
      - cheisel@kabbage.com
    on_success: change
    on_failure: change
